# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

main:
  - name: Home
    url: /
    weight: 10
  - name: About
    url: about
    weight: 15
  - name: News
    url: post
    weight: 20
  - name: Partners & People
    url: partners
    weight: 30
  # - name: Events
  #   url: event
  #   weight: 40
  # - name: Press
  #   url: press
  #   weight: 50
  - name: Publications
    url: publication
    weight: 60
  - name: Gallery
    url: gallery
    weight: 70
  - name: Contact
    url: contact
    weight: 80
